AppBundle\Entity\Clients:
    type: entity
    table: clients
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        clientId:
            type: string
            nullable: false
            length: 36
            fixed: false
            comment: ''
            column: client_id
        clientName:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: client_name
    lifecycleCallbacks: {  }
