AppBundle\Entity\Invoicelineitems:
    type: entity
    table: invoicelineitems
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        invoiceNum:
            type: string
            nullable: false
            length: 11
            fixed: false
            comment: ''
            column: invoice_num
        productId:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: product_id
        qty:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            comment: ''
            default: '0.00'
        price:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            comment: ''
    lifecycleCallbacks: {  }
