AppBundle\Entity\Invoices:
    type: entity
    table: invoices
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        invoiceDate:
            type: date
            nullable: false
            comment: ''
            column: invoice_date
        clientId:
            type: string
            nullable: false
            length: 36
            fixed: false
            comment: ''
            column: client_id
        invoiceNum:
            type: string
            nullable: false
            length: 11
            fixed: false
            comment: ''
            column: invoice_num
    lifecycleCallbacks: {  }
