AppBundle\Entity\Products:
    type: entity
    table: products
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        productId:
            type: string
            nullable: false
            length: 70
            fixed: false
            comment: ''
            column: product_id
        clientId:
            type: string
            nullable: false
            length: 36
            fixed: false
            comment: ''
            column: client_id
        productDescription:
            type: string
            nullable: false
            length: 252
            fixed: false
            comment: ''
            column: product_description
    lifecycleCallbacks: {  }
